# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_index_window(object):
    def setupUi(self, index_window):
        index_window.setObjectName("index_window")
        index_window.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        index_window.setFont(font)
        self.centralwidget = QtWidgets.QWidget(index_window)
        self.centralwidget.setObjectName("centralwidget")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(140, 360, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(280, 240, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Agave Nerd Font Mono")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.register_button = QtWidgets.QPushButton(self.centralwidget)
        self.register_button.setGeometry(QtCore.QRect(520, 360, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.register_button.setFont(font)
        self.register_button.setObjectName("register_button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 40, 291, 161))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/image/1.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(90, 220, 631, 291))
        self.frame.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 374, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(530, 375, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setLineWidth(1)
        self.label_4.setObjectName("label_4")
        self.frame.raise_()
        self.login_button.raise_()
        self.label.raise_()
        self.register_button.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        index_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(index_window)
        self.statusbar.setObjectName("statusbar")
        index_window.setStatusBar(self.statusbar)

        self.retranslateUi(index_window)
        QtCore.QMetaObject.connectSlotsByName(index_window)

    def retranslateUi(self, index_window):
        _translate = QtCore.QCoreApplication.translate
        index_window.setWindowTitle(_translate("index_window", "校园卡管理系统"))
        self.login_button.setText(_translate("index_window", "登录"))
        self.label.setText(_translate("index_window", "校园卡管理系统"))
        self.register_button.setText(_translate("index_window", "注册"))
        self.label_3.setText(_translate("index_window", "🔑"))
        self.label_4.setText(_translate("index_window", "📝"))
        self.label_3.setAttribute(QtCore.Qt.WidgetAttribute.WA_TransparentForMouseEvents,True)
        self.label_4.setAttribute(QtCore.Qt.WidgetAttribute.WA_TransparentForMouseEvents, True)
import image_rc
